# Generated by Django 5.2.7 on 2025-11-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('is_new', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
